name: Coverage

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  statuses: write

jobs:
  coveralls:
    name: Coveralls
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate coverage
        run: npm run test:cov

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage/lcov.info
